# Generated by Django 3.0.7 on 2020-10-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bongRestApi', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('userProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bongRestApi.UserProfile')),
            ],
        ),
    ]
