# Generated by Django 3.0.7 on 2020-10-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bongRestApi', '0006_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
